default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: goliath
  password: "dev-admin-goliath"
  host: localhost
  port: 5432

development:
  <<: *default
  database: goliath_online_development

test:
  <<: *default
  database: goliath_online_test

production:
  <<: *default
  database: goliath_online_production
  username: goliath_online
  password: <%= ENV['GOLIATH_ONLINE_DATABASE_PASSWORD'] %>
